"""Path helpers for the install / uninstall skills.

The skills ask Python "where are you installed?" and copy files based on the
answer. Centralizing the path knowledge here keeps the skill bodies from
hardcoding package internals and makes future renames a one-place change.
"""
from __future__ import annotations

import pathlib
import sys


# Files inside the package that are NOT needed in the Remote Script copy
# (they pull in heavyweight deps like the FastMCP package, which Live's
# embedded Python does not have).
REMOTE_SCRIPT_EXCLUDE: tuple[str, ...] = (
    "server.py",        # FastMCP-dependent
    "cli",              # console-script entry; pulls in serve.py which imports server.py
    "tests",            # outside the package proper, but covered for safety
    "__pycache__",      # bytecode caches; never relevant on install
)


def package_root() -> pathlib.Path:
    """Filesystem path to the installed ``hallucinote_mcp`` package."""
    import hallucinote_mcp

    init_path = pathlib.Path(hallucinote_mcp.__file__).resolve()
    return init_path.parent


def remote_script_stub_text() -> str:
    """The tiny ``__init__.py`` Live loads as the Control Surface entry point.

    Lives at ``<User Library>/Remote Scripts/Hallucinote/__init__.py``. Uses
    a **relative import** because Live's loader adds the ``Remote Scripts``
    directory to ``sys.path``, so ``Hallucinote`` is the importable package
    and ``hallucinote_mcp`` is its subpackage — not a top-level name on
    sys.path.
    """
    return (
        "# Auto-generated by /ableton-install-mcp — do not edit.\n"
        "# This stub re-exports the Control Surface entry point from the\n"
        "# vendored hallucinote_mcp package living next to this file.\n"
        "from __future__ import absolute_import\n"
        "\n"
        "from .hallucinote_mcp.remote_script import create_instance  # noqa: F401\n"
    )


def default_user_library() -> pathlib.Path:
    """Best-effort User Library location for the running platform.

    Used only as a starting hint for the install skill; the user can override.
    """
    home = pathlib.Path.home()
    if sys.platform == "darwin":
        return home / "Music" / "Ableton" / "User Library"
    if sys.platform == "win32":
        return home / "Documents" / "Ableton" / "User Library"
    # Linux: Ableton Live doesn't officially ship for Linux, but Bitwig users
    # sometimes ask. Best guess.
    return home / "Ableton" / "User Library"


def remote_script_install_dir(user_library: pathlib.Path) -> pathlib.Path:
    """``<User Library>/Remote Scripts/Hallucinote``."""
    return user_library / "Remote Scripts" / "Hallucinote"


def describe_install_layout(user_library: pathlib.Path) -> str:
    """Human-readable summary of what the install will create.

    Used by the install skill to preview the layout before touching the
    filesystem.
    """
    target = remote_script_install_dir(user_library)
    return (
        f"{target}/\n"
        f"  __init__.py          (Control Surface entry stub)\n"
        f"  hallucinote_mcp/     (vendored package, excludes {', '.join(REMOTE_SCRIPT_EXCLUDE)})\n"
    )


__all__ = [
    "REMOTE_SCRIPT_EXCLUDE",
    "package_root",
    "remote_script_stub_text",
    "default_user_library",
    "remote_script_install_dir",
    "describe_install_layout",
]
