"""Path helpers for the install / uninstall skills.

The skills ask Python "where are you installed, where's Live, what's already on
disk?" and copy files based on the answers. Centralizing this here keeps the
skill bodies from hardcoding package internals and makes the detection logic
testable.

Scope: read-only detection and path math. No filesystem mutation — the skills
do the copying / editing themselves, the helpers just hand them the answers.
"""
from __future__ import annotations

import dataclasses
import hashlib
import json
import os
import pathlib
import shutil
import subprocess
import sys


# Files at the package root (anchored) that must NOT be copied. The anchor
# is load-bearing: `server.py` exists both at the package root (FastMCP-
# dependent — Live's embedded Python can't import it) and inside
# `remote_script/` (the Control Surface entrypoint Live LOADS). An
# unanchored "server.py" exclude strips both — silently breaking the install.
REMOTE_SCRIPT_EXCLUDE_TOP_LEVEL_FILES: tuple[str, ...] = (
    "server.py",
)

# Directory names to exclude wherever they appear in the source tree.
REMOTE_SCRIPT_EXCLUDE_DIRS_ANY: tuple[str, ...] = (
    "cli",              # console-script entry; pulls in serve.py which imports server.py
    "tests",            # outside the package proper, but covered for safety
    "__pycache__",      # bytecode caches; never relevant on install
    "m4l",              # M4L device source — installed separately into
                        # `Presets/Audio Effects/Max Audio Effect/` via the
                        # install skill's analyzer-copy step. If included
                        # here, Live's browser indexes BOTH locations and
                        # shows the device twice, leading to "which one am
                        # I editing?" confusion (audio-analysis MVP Chunk 2
                        # sub-chunk 2B hit this — see learnings.md).
)

# File globs to exclude wherever they appear.
REMOTE_SCRIPT_EXCLUDE_FILE_GLOBS_ANY: tuple[str, ...] = (
    "*.pyc",
)


# --- Package introspection -------------------------------------------------

def package_root() -> pathlib.Path:
    """Filesystem path to the installed ``hallucinote_mcp`` package."""
    import hallucinote_mcp

    init_path = pathlib.Path(hallucinote_mcp.__file__).resolve()
    return init_path.parent


def remote_script_stub_text() -> str:
    """The tiny ``__init__.py`` Live loads as the Control Surface entry point.

    Lives at ``<User Library>/Remote Scripts/Hallucinote/__init__.py``. Uses
    a **relative import** because Live's loader adds the ``Remote Scripts``
    directory to ``sys.path``, so ``Hallucinote`` is the importable package
    and ``hallucinote_mcp`` is its subpackage — not a top-level name on
    sys.path.
    """
    return (
        "# Auto-generated by /ableton-mcp-install — do not edit.\n"
        "# This stub re-exports the Control Surface entry point from the\n"
        "# vendored hallucinote_mcp package living next to this file.\n"
        "from __future__ import absolute_import\n"
        "\n"
        "from .hallucinote_mcp.remote_script import create_instance  # noqa: F401\n"
    )


# --- User Library detection ------------------------------------------------

def _windows_documents_candidates() -> list[pathlib.Path]:
    """Plausible Documents folders on Windows, most likely first.

    OneDrive redirection is the default on modern Windows 10/11 installs —
    Documents may resolve to ``%OneDrive%\\Documents`` rather than
    ``%USERPROFILE%\\Documents``. Some users opt out, some are mid-migration
    with both folders simultaneously populated. We probe all of them in a
    deterministic order so the install skill can pick the one Live is
    actually writing to.
    """
    seen: set[str] = set()
    out: list[pathlib.Path] = []

    def _add(p: pathlib.Path) -> None:
        key = str(p).lower()
        if key not in seen:
            seen.add(key)
            out.append(p)

    # Explicit OneDrive env vars set by the OneDrive client — most reliable
    # signal of where Documents currently lives.
    onedrive_env_active = False
    for var in ("OneDrive", "OneDriveConsumer", "OneDriveCommercial"):
        val = os.environ.get(var)
        if val:
            _add(pathlib.Path(val) / "Documents")
            onedrive_env_active = True

    bases: list[pathlib.Path] = [pathlib.Path.home()]
    user_profile = os.environ.get("USERPROFILE")
    if user_profile:
        up = pathlib.Path(user_profile)
        if up not in bases:
            bases.append(up)

    for base in bases:
        # Probe `<base>/OneDrive/Documents` only if OneDrive is signalled —
        # by env var (active install) or by the directory existing on
        # disk. Avoids surfacing a stale empty dir on systems that
        # uninstalled OneDrive.
        candidate_od = base / "OneDrive" / "Documents"
        if onedrive_env_active or candidate_od.exists():
            _add(candidate_od)
        _add(base / "Documents")               # plain Documents

    return out


def candidate_user_libraries() -> list[pathlib.Path]:
    """All plausible User Library paths for this platform, in priority order.

    The install / uninstall skills use this to *probe* — if a candidate
    exists on disk it's treated as the User Library; otherwise the skill
    falls back to asking the user. The first entry is the canonical
    platform default (used when none of the candidates exist on disk).
    """
    if sys.platform == "darwin":
        return [pathlib.Path.home() / "Music" / "Ableton" / "User Library"]
    if sys.platform == "win32":
        return [
            doc / "Ableton" / "User Library"
            for doc in _windows_documents_candidates()
        ]
    # Linux: Live doesn't officially ship for Linux. Best guess for Wine /
    # CrossOver users; the skill warns rather than promising it works.
    return [pathlib.Path.home() / "Ableton" / "User Library"]


def default_user_library() -> pathlib.Path:
    """Best-effort User Library — first existing candidate, else platform default.

    The install skill uses this as the initial guess. The user can override
    if they've moved their User Library via Live's Preferences → Library
    → Location of User Library.
    """
    candidates = candidate_user_libraries()
    for cand in candidates:
        if cand.exists():
            return cand
    return candidates[0]


def remote_script_install_dir(user_library: pathlib.Path | str) -> pathlib.Path:
    """``<User Library>/Remote Scripts/Hallucinote``.

    Accepts ``str`` too — the install skill body interpolates user-typed
    paths into ``python -c`` invocations, so strings come in naturally.
    """
    return pathlib.Path(user_library) / "Remote Scripts" / "Hallucinote"


ANALYZER_AMXD_FILENAME = "HallucinoteAnalyzer.amxd"
"""The M4L device file shipped under `hallucinote_mcp/m4l/`. Filename
(minus extension) surfaces in Live as ``device.name`` on freshly-loaded
instances; `analyzer.setup.ensure_analyzers_loaded` detects existing
instances by requiring both ``device.class_display_name == "Max Audio
Effect"`` AND ``device.name`` matching this filename's stem."""


def analyzer_amxd_source_path() -> pathlib.Path:
    """Source location of the bundled ``HallucinoteAnalyzer.amxd``.

    The install skill copies from this path into the User Library's
    Max Audio Effect Presets directory. Keeping the path computation
    here (testable) so the skill body stays declarative.
    """
    return package_root() / "m4l" / ANALYZER_AMXD_FILENAME


def analyzer_install_dir(user_library: pathlib.Path | str) -> pathlib.Path:
    """Where Live looks for user-installed Max Audio Effect devices.

    ``<User Library>/Presets/Audio Effects/Max Audio Effect/`` — devices
    in this directory appear in Live's browser under
    ``Audio Effects > Max Audio Effect`` and can be loaded by
    ``browser.load_item`` from anywhere in the LOM tree.
    """
    return (
        pathlib.Path(user_library)
        / "Presets"
        / "Audio Effects"
        / "Max Audio Effect"
    )


def analyzer_install_target(user_library: pathlib.Path | str) -> pathlib.Path:
    """Full filesystem destination for the installed ``HallucinoteAnalyzer.amxd``."""
    return analyzer_install_dir(user_library) / ANALYZER_AMXD_FILENAME


def installed_analyzer_amxd(
    user_library: pathlib.Path | str,
) -> pathlib.Path | None:
    """Path to the installed analyzer if present in this User Library, else None.

    Used by the install skill to detect drift (vendored vs installed
    file size / modification time mismatch) and by the uninstall
    skill to know what to remove.
    """
    target = analyzer_install_target(user_library)
    return target if target.is_file() else None


def analyzer_fingerprint(path: pathlib.Path | str) -> str | None:
    """Content fingerprint of an ``.amxd`` device — 12 hex chars of sha256, or ``None``.

    The ``.amxd`` is a **binary container**, so this hashes the raw bytes
    directly and deliberately does *not* reuse the text-normalizing
    :func:`hallucinote_mcp.compute_version_for` path (which the Remote Script
    uses): CRLF→LF normalization would corrupt binary content, and that path's
    NUL-byte guard already excludes such files from line-ending munging. A pure
    byte hash is the correct fingerprint for a binary device.

    Returns ``None`` when ``path`` isn't a readable file (absent install or a
    permission error) so the caller can distinguish "not installed" from a real
    fingerprint — mirroring :func:`installed_remote_script_version`'s tri-state.
    The 12-char width matches the Remote Script fingerprint suffix for
    consistency in preflight output; collision risk at this width is negligible
    for the drift-detection use (the alternative on a hash clash is a redundant
    re-copy, never a silent skip of a genuinely-different device).
    """
    path = pathlib.Path(path)
    if not path.is_file():
        return None
    hasher = hashlib.sha256()
    try:
        with path.open("rb") as fh:
            for chunk in iter(lambda: fh.read(65536), b""):
                hasher.update(chunk)
    except OSError:
        return None
    return hasher.hexdigest()[:12]


def analyzer_source_fingerprint() -> str | None:
    """Fingerprint of the bundled source ``HallucinoteAnalyzer.amxd`` (or ``None``).

    The reference the install skill compares an installed device against — if it
    matches :func:`installed_analyzer_fingerprint` the device is byte-identical
    and the copy + overwrite prompt can be skipped entirely.
    """
    return analyzer_fingerprint(analyzer_amxd_source_path())


def installed_analyzer_fingerprint(
    user_library: pathlib.Path | str,
) -> str | None:
    """Fingerprint of the analyzer installed in ``user_library`` (or ``None`` if absent).

    Surfaced through preflight alongside :func:`analyzer_source_fingerprint` so
    the install skill can detect that the installed ``.amxd`` is byte-identical
    to (or has drifted from) the bundled source — parity with the Remote
    Script's ``matches_mcp_server`` drift signal, but for the binary device.
    """
    installed = installed_analyzer_amxd(user_library)
    if installed is None:
        return None
    return analyzer_fingerprint(installed)


def max_for_live_available(live_version: str | None = None) -> bool | None:
    """Best-effort probe for whether Max for Live (M4L) is available.

    The HallucinoteAnalyzer is an M4L device; without an M4L runtime
    Live can't load it. M4L ships only with Live Suite — the install
    skill warns / refuses if Live isn't Suite.

    Returns:
      - ``True``  — strong evidence M4L is installed (Live Suite preference
        file present, or platform-specific Max install detected).
      - ``False`` — strong evidence M4L is NOT installed (Live edition
        is detected and isn't Suite).
      - ``None``  — can't tell. Surface as "ask the user" in the skill;
        many setups (custom installs, Wine, etc.) defeat the heuristics.

    Today we return ``None`` unconditionally — the heuristics that
    distinguish Suite from Standard from Lite aren't reliable across
    Live versions, and a wrong ``False`` would refuse a valid install.
    The install skill prompts the user. This signature lets the skill
    body assume the contract for future tightening without re-wiring.
    """
    # `live_version` is reserved for future per-version probes (e.g.,
    # Live 12 surfaces edition info in a different file than Live 11).
    _ = live_version
    return None


def installed_remote_script_version(user_library: pathlib.Path | str) -> str | None:
    """The vendored Remote Script's ``__version__`` string, or ``None`` if absent.

    Reads ``<User Library>/Remote Scripts/Hallucinote/hallucinote_mcp/__init__.py``
    and parses ``BASE_VERSION`` + recomputes the content fingerprint via
    :func:`hallucinote_mcp.compute_version_for`. The result string is
    directly comparable to the running server's ``__version__`` — a match
    means the next runtime handshake will succeed.

    Surfaced through preflight (``remote_script.candidates[*].version``)
    so the install / uninstall skills can detect drift before Live
    rejects a dispatch (W12-D MCP/Live drift visibility).
    """
    from . import compute_version_for

    vendored_pkg = remote_script_install_dir(user_library) / "hallucinote_mcp"
    if not vendored_pkg.is_dir():
        return None
    return compute_version_for(vendored_pkg)


# --- Ableton Live detection ------------------------------------------------

def _live_preferences_root() -> pathlib.Path | None:
    """Root directory containing per-version Live preferences (or None)."""
    if sys.platform == "darwin":
        return pathlib.Path.home() / "Library" / "Preferences" / "Ableton"
    if sys.platform == "win32":
        appdata = os.environ.get("APPDATA")
        if not appdata:
            return None
        return pathlib.Path(appdata) / "Ableton"
    return None


def installed_live_versions() -> list[str]:
    """List installed Live versions, e.g. ``["11.3.21", "12.0.5"]``.

    Inferred from per-version preference directories (``Live X.Y.Z/``), which
    Live creates on first launch. An empty list means either no Live install
    or Live has never been launched on this machine — the skill asks in that
    case rather than guessing.
    """
    root = _live_preferences_root()
    if root is None or not root.exists():
        return []
    versions: list[str] = []
    prefix = "Live "
    for child in root.iterdir():
        if child.is_dir() and child.name.startswith(prefix):
            versions.append(child.name[len(prefix):])
    versions.sort()
    return versions


def live_log_path(version: str) -> pathlib.Path | None:
    """Path to Live's ``Log.txt`` for the given version, if locatable.

    Used by the install skill's troubleshooting section so the agent can
    point at the exact log rather than describing where it lives.
    """
    root = _live_preferences_root()
    if root is None:
        return None
    return root / f"Live {version}" / "Log.txt"


def live_is_running() -> bool | None:
    """``True`` if Live appears to be running, ``False`` if not, ``None`` if unknown.

    Best-effort: ``pgrep`` on macOS, ``tasklist`` on Windows. If the probe
    fails (binary missing, timeout, permission denied), returns ``None``
    rather than guessing — the skill treats ``None`` as "ask the user".
    """
    if sys.platform == "darwin":
        try:
            out = subprocess.run(
                ["pgrep", "-i", "-f", "Ableton Live"],
                capture_output=True, text=True, timeout=5,
            )
        except (FileNotFoundError, subprocess.SubprocessError):
            return None
        if out.returncode == 0:
            return bool(out.stdout.strip())
        if out.returncode == 1:
            return False
        return None
    if sys.platform == "win32":
        try:
            # `tasklist /FI "IMAGENAME eq <pattern>"` doesn't support glob
            # wildcards in `eq` mode — the filter would silently match
            # nothing while the substring check below carries the actual
            # detection. Drop the (no-op) filter and substring-match the
            # full process list instead.
            out = subprocess.run(
                ["tasklist"],
                capture_output=True, text=True, timeout=5,
            )
        except (FileNotFoundError, subprocess.SubprocessError):
            return None
        if out.returncode != 0:
            return None
        # Live's process image is "Ableton Live <edition>.exe" (Suite,
        # Standard, etc.) — substring match is the structurally correct
        # detection without leaning on the tasklist filter.
        return "Ableton Live" in out.stdout
    return None


# --- hallucinote-mcp command + MCP config detection -----------------------

def hallucinote_mcp_command() -> tuple[pathlib.Path | None, bool]:
    """Locate the ``hallucinote-mcp`` console script and report whether it's on PATH.

    Returns ``(path, on_path)``:
      - ``(Path, True)``  — found via ``shutil.which``; the MCP config can
        use the bare command name.
      - ``(Path, False)`` — found only in a venv's ``bin`` / ``Scripts`` dir
        that isn't on the user's PATH; the MCP config must use the absolute
        path or Claude Code won't be able to launch the server.
      - ``(None, False)`` — not found anywhere; the install skill must stop
        and tell the user to ``pip install hallucinote-mcp``.

    The tri-state matters because the previous "Path | None" return
    couldn't distinguish the venv-fallback case, leading the install skill
    to write a bare command into the config even when only an absolute
    path would resolve.
    """
    found = shutil.which("hallucinote-mcp")
    if found:
        return pathlib.Path(found).resolve(), True

    exe_dir = pathlib.Path(sys.executable).parent
    bin_name = "hallucinote-mcp.exe" if sys.platform == "win32" else "hallucinote-mcp"

    # Unix venvs put console scripts next to python; Windows venvs use
    # Scripts/ next to python.exe.
    candidates = [exe_dir / bin_name]
    if sys.platform == "win32":
        candidates.append(exe_dir / "Scripts" / bin_name)
    else:
        # Some Python installs (e.g., Homebrew) keep scripts in ../bin
        candidates.append(exe_dir.parent / "bin" / bin_name)

    for cand in candidates:
        if cand.exists():
            return cand.resolve(), False
    return None, False


def uv_runtime() -> tuple[pathlib.Path | None, str | None]:
    """Locate the ``uv`` binary and read its version. Returns ``(path, version)``.

    ``uv`` is the one prerequisite for the plugin-bundled MCP server: the plugin
    launches it with ``uv run --frozen --all-packages`` into a per-plugin env
    (INS-7V2D), so if ``uv`` isn't resolvable the server can't start. The install
    skill's preflight surfaces this so the user can ``brew install uv`` (or the
    curl bootstrap) before relying on the bridge.

    ``(None, None)`` when uv isn't found; ``(Path, None)`` when found but
    ``uv --version`` couldn't be read.

    Caveat: this probes the *install-process* PATH (``shutil.which``). Claude Code
    spawns stdio MCP servers with a sanitized environment, so uv being here is a
    strong proxy — but the authoritative "does the bridge launch?" check is the
    live spawn (tracked in operator-verification).
    """
    found = shutil.which("uv")
    if not found:
        return None, None
    path = pathlib.Path(found).resolve()
    try:
        out = subprocess.run(
            [str(path), "--version"], capture_output=True, text=True, timeout=5,
        )
    except (FileNotFoundError, subprocess.SubprocessError):
        return path, None
    if out.returncode == 0:
        return path, (out.stdout.strip() or None)
    return path, None


def mcp_config_global_path() -> pathlib.Path:
    """``~/.claude.json`` — global Claude Code config."""
    return pathlib.Path.home() / ".claude.json"


def mcp_config_local_path(cwd: pathlib.Path | None = None) -> pathlib.Path:
    """``.mcp.json`` in ``cwd`` (defaults to the current working directory)."""
    base = cwd if cwd is not None else pathlib.Path.cwd()
    return base / ".mcp.json"


def _read_json(path: pathlib.Path) -> dict | None:
    """Parse a JSON file, returning ``None`` if missing or malformed.

    Distinguishing "missing" from "malformed" is done by the callers that
    care — :func:`malformed_mcp_config_files` does its own parse.

    `UnicodeDecodeError` (a `ValueError` subclass, not an `OSError`) needs
    its own clause: a config file written in a non-UTF-8 encoding is a
    "malformed" case from our perspective, not a crash one.
    """
    if not path.exists():
        return None
    try:
        loaded = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError, UnicodeDecodeError):
        return None
    return loaded if isinstance(loaded, dict) else None


@dataclasses.dataclass(frozen=True)
class MCPConfigEntry:
    """A located ``hallucinote-mcp`` entry inside a config file.

    ``json_pointer`` is the chain of keys to walk to reach the entry. The
    uninstall skill deletes the entry by walking the pointer; the install
    skill uses it to detect which scope an existing entry lives in before
    asking whether to replace.

    Examples:
        - ``("mcpServers", "hallucinote-mcp")`` — top-level entry in
          ``.mcp.json`` or in the global ``~/.claude.json``.
        - ``("projects", "/path/to/proj", "mcpServers", "hallucinote-mcp")``
          — per-project entry that ``claude mcp add`` writes to the global
          config when the user uses the default ``local`` scope.
    """

    path: pathlib.Path
    json_pointer: tuple[str, ...]

    def as_dict(self) -> dict:
        return {"path": str(self.path), "json_pointer": list(self.json_pointer)}


def existing_mcp_config_files(cwd: pathlib.Path | str | None = None) -> list[MCPConfigEntry]:
    """Located ``hallucinote-mcp`` entries across all known config scopes.

    Used by the uninstall skill to find every place we need to edit
    without asking the user. Scans:

    - ``.mcp.json`` in ``cwd`` (``mcpServers.hallucinote-mcp``).
    - ``~/.claude.json`` top-level (``mcpServers.hallucinote-mcp``) — used
      when the user opted into global scope during install.
    - ``~/.claude.json`` per-project
      (``projects.<cwd>.mcpServers.hallucinote-mcp``) — the default scope
      written by ``claude mcp add``. A previous version missed this and
      would silently orphan the registration.

    Each hit is a :class:`MCPConfigEntry` carrying the file path and the
    JSON pointer to walk. Malformed files are skipped — surface them via
    :func:`malformed_mcp_config_files` separately so the user can decide
    whether to fix or overwrite.
    """
    cwd = pathlib.Path(cwd) if cwd is not None else pathlib.Path.cwd()
    # `claude mcp add` records the project key as whatever cwd string was
    # active at the time, which may differ from the current invocation's
    # cwd by symlink resolution (macOS `/var` vs `/private/var`) or
    # Windows path-case. Try both the as-given and the resolved form so a
    # cwd-shape mismatch doesn't silently orphan an existing registration.
    cwd_candidates: list[str] = [str(cwd)]
    try:
        resolved = str(cwd.resolve())
    except OSError:
        resolved = None
    if resolved is not None and resolved not in cwd_candidates:
        cwd_candidates.append(resolved)
    out: list[MCPConfigEntry] = []

    # .mcp.json — top-level only (project files don't nest scopes).
    local_path = mcp_config_local_path(cwd)
    data = _read_json(local_path)
    if isinstance(data, dict):
        servers = data.get("mcpServers")
        if isinstance(servers, dict) and "hallucinote-mcp" in servers:
            out.append(MCPConfigEntry(local_path, ("mcpServers", "hallucinote-mcp")))

    # ~/.claude.json — top-level entry plus the per-project scope that
    # ``claude mcp add`` (the CLI) writes to by default.
    global_path = mcp_config_global_path()
    data = _read_json(global_path)
    if isinstance(data, dict):
        servers = data.get("mcpServers")
        if isinstance(servers, dict) and "hallucinote-mcp" in servers:
            out.append(MCPConfigEntry(global_path, ("mcpServers", "hallucinote-mcp")))
        projects = data.get("projects")
        if isinstance(projects, dict):
            for cwd_key in cwd_candidates:
                project = projects.get(cwd_key)
                if not isinstance(project, dict):
                    continue
                proj_servers = project.get("mcpServers")
                if isinstance(proj_servers, dict) and "hallucinote-mcp" in proj_servers:
                    out.append(MCPConfigEntry(
                        global_path,
                        ("projects", cwd_key, "mcpServers", "hallucinote-mcp"),
                    ))
                    break  # don't double-report the same registration
    return out


def malformed_mcp_config_files(cwd: pathlib.Path | str | None = None) -> list[pathlib.Path]:
    """Config files that exist but failed to parse as JSON.

    Surfaced by both skills so the user can fix them before we proceed —
    overwriting a malformed config could destroy hand-edited state. Only
    JSON-decode failures are reported; unreadable files (permission errors)
    surface later as the actual write attempt fails.
    """
    cwd = pathlib.Path(cwd) if cwd is not None else pathlib.Path.cwd()
    out: list[pathlib.Path] = []
    for path in (mcp_config_local_path(cwd), mcp_config_global_path()):
        if not path.exists():
            continue
        try:
            json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, UnicodeDecodeError):
            # UnicodeDecodeError covers configs written in a non-UTF-8
            # encoding — treat them the same as JSON parse failures so
            # the user gets a single "malformed config" surface.
            out.append(path)
        except OSError:
            continue
    return out


__all__ = [
    "ANALYZER_AMXD_FILENAME",
    "MCPConfigEntry",
    "REMOTE_SCRIPT_EXCLUDE_DIRS_ANY",
    "REMOTE_SCRIPT_EXCLUDE_FILE_GLOBS_ANY",
    "REMOTE_SCRIPT_EXCLUDE_TOP_LEVEL_FILES",
    "analyzer_amxd_source_path",
    "analyzer_fingerprint",
    "analyzer_install_dir",
    "analyzer_install_target",
    "analyzer_source_fingerprint",
    "candidate_user_libraries",
    "default_user_library",
    "existing_mcp_config_files",
    "hallucinote_mcp_command",
    "installed_analyzer_amxd",
    "installed_analyzer_fingerprint",
    "installed_live_versions",
    "installed_remote_script_version",
    "live_is_running",
    "live_log_path",
    "malformed_mcp_config_files",
    "max_for_live_available",
    "mcp_config_global_path",
    "mcp_config_local_path",
    "package_root",
    "remote_script_install_dir",
    "remote_script_stub_text",
    "uv_runtime",
]
